routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

Route::resource('roles','RoleController');
Route::resource('permissions','PermissionController');

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;

class PermissionController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::withCount('roles')->get();
        $roles = Role::where('name', '!=', Role::ADMIN)->get();

        return view('permissions.index', [
            'permissions' => $permissions,
            'roles' => $roles,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::get();

        return view('permissions.create')->with('roles', $roles);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:40',
        ]);

        $name = $request->name;
        $permission = new Permission();
        $permission->name = $name;

        $roles = $request->roles;

        $permission->save();

        if (!empty($request['roles'])) {
            foreach ($roles as $role) {
                $r = Role::where('id', '=', $role)->firstOrFail();

                $permission = Permission::where('name', '=', $name)->first();
                $r->givePermissionTo($permission);
            }
        }

        return redirect()->route('permissions.index')
            ->with('status', 'Permission ' . $permission->name . ' added!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function edit(Permission $permission)
    {

        $roles = Role::where('name', '!=', Role::ADMIN)->get();

        return view('permissions.edit', [
            'permission' => $permission->load(['roles']),
            'roles' => $roles
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Permission $permission)
    {

        $this->validate($request, [
            'name' => 'required|max:40',
        ]);
        $input = $request->only('name');
        $permission->fill($input)->save();

        if ($request->roles) {
            $permission->syncRoles($request->roles);
        } else {
            $permission->roles()->detach();
        }

        return redirect()->route('permissions.index')
            ->with('status', 'Permission ' . $permission->name . ' updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $permission = Permission::findOrFail($id);
        //Make it impossible to delete this specific permission 
        if ($permission->name == "full_control") {
            return redirect()->route('permissions.index')
                ->with('status', 'Cannot delete this Permission!');
        }
        $permission->delete();

        return redirect()->route('permissions.index')
            ->with('status', 'Permission deleted!');
    }
}

resources/views/permissions/edit.blade.php
@extends('layouts.app', ['title' => 'Edit Permission'])

@section('content')

@include('layouts.partials.header', ['title' => 'Edit '.$permission->name])
<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <form method="POST" action="{{route('permissions.update',$permission)}}">
                        @method('PUT')
                        @csrf
                        <!-- Role Name -->
                        <div class="form-row mb-2">
                            <label class="col-md-2 col-form-label">Permission Name</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" name="name" value='{{ $permission->name }}'>
                            </div>
                        </div>
                        <div class="form-row">
                            <label class="col-md-2 col-form-label">Roles</label>
                            <div class="col-md-10">
                                @if($roles->count() > 0)
                                <div class="form-group">
                                    <div class="selectgroup selectgroup-pills">
                                        @foreach($roles as $role)
                                        <label class="selectgroup-item">
                                            <input type="checkbox" name="roles[]" class="selectgroup-input" value="{{ $role->id }}" {{ in_array($role->id,$permission->roles->pluck('id')->toArray())?'checked':'' }}>
                                            <span class="selectgroup-button">{{ ucfirst($role->name) }}</span>
                                        </label>
                                        @endforeach
                                    </div>
                                </div>
                                @else
                                <p class="mb-0">No Role created.</p>
                                @endif
                            </div>
                        </div>
                        <div class="d-flex justify-content-end">
                            <div>
                                <button type="button" class="btn btn-danger" onclick="event.preventDefault();
                                    document.getElementById('delete-permission-form').submit();">
                                    Delete
                                </button>
                                <button type="submit" class="btn btn-success">Update</button>
                            </div>
                        </div>
                    </form>
                    <form id="delete-permission-form" action="{{ route('permissions.destroy',$permission) }}" method="POST" style="display: none;">
                        @method('DELETE')
                        @csrf
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/permissions/index.blade.php
@extends('layouts.app', ['title' => 'Permissions'])

@section('content')
@include('layouts.partials.header', ['title' => 'Manage Permissions'])
<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Permissions</h3>
                        </div>
                        <div class="col-4 text-right">
                            <button class="btn btn-sm btn-primary" data-toggle="modal" data-target="#modal-create-permission">Add permission</button>
                        </div>
                    </div>
                </div>

                <div class="col-12">
                    @if (session('status'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('status') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif
                </div>

                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        @if($permissions->count() > 0)
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Roles</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($permissions as $permission)
                            <tr>
                                <td>
                                    {{ $permission->name }}
                                </td>
                                <td>
                                    {{ $permission->roles_count }}
                                </td>
                                <!-- Revoke Button -->
                                <td>
                                    <a href="{{ route('permissions.edit', $permission) }}" class="btn btn-primary btn-sm">
                                        <i class="far fa-edit"></i>
                                        Edit
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                        @else
                        <tr>
                            <td colspan="5">No permission created.</td>
                        </tr>
                        @endif
                    </table>
                </div>
            </div>
        </div>
    </div>
    @include('layouts.footers.auth')
</div>

<!-- Create Role Modal -->
<div class="modal fade" id="modal-create-permission" tabindex="-1" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    Create Permission
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>

            <div class="modal-body">
                <!-- Create Permission Form -->
                <form id="add-permission-form" role="form" method="POST" action="{{ route('permissions.store') }}">
                    @csrf
                    <!-- Name -->
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Permission Name</label>
                        <div class="col-md-10">
                            <input id="create-unit-name" type="text" class="form-control" name="name">
                        </div>
                    </div>
                    <!-- Permission-->
                    <div class="form-row">
                        <label class="col-md-2 col-form-label">Roles</label>
                        <div class="col-md-10">
                            @if($roles->count() > 0)
                            <div class="form-group">
                                <div class="selectgroup selectgroup-pills">
                                    @foreach($roles as $role)
                                    <label class="selectgroup-item">
                                        <input type="checkbox" name="roles[]" class="selectgroup-input" value="{{ $role->id }}">
                                        <span class="selectgroup-button">{{ ucfirst($role->name) }}</span>
                                    </label>
                                    @endforeach
                                </div>
                            </div>
                            @else
                            <p class="mb-0">No Role created.</p>
                            @endif
                        </div>
                    </div>
                </form>
            </div>

            <!-- Modal Actions -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="add-permission-form-submit" type="button" class="btn btn-primary">
                    Create
                </button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script type="text/javascript">
    $('#add-permission-form-submit').on('click', function(event) {
        $('#add-permission-form').submit();
    });
</script>
@endpush