routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

Route::resource('roles','RoleController');
Route::resource('permissions','PermissionController');

app/Role.php
<?php

namespace App;

use Spatie\Permission\Models\Role as Model;

class Role extends Model
{
    const ADMIN = 'System Admin';
    const MODERATOR = 'Moderator';
    const CLIENT = 'Developer User';
    const DEVELOPER = 'IT Developer (for API)';
    const LAWFIRM = 'Law Firm User';
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;

class RoleController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::where('name', '!=', Role::ADMIN)->get();
        $permissions = Permission::all();

        $grouped_permissions = $this->groupPermission($permissions);

        return view('roles.index', [
            'roles' => $roles,
            'permissions' => $grouped_permissions
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all();

        $grouped_permissions = $this->groupPermission($permissions);

        return view('roles.create')->with('permissions', $grouped_permissions);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validate name and permissions field
        $this->validate(
            $request,
            [
                'name' => 'required|unique:roles|max:20'
            ]
        );

        $name = strtolower($request->name);
        $role = new Role();
        $role->name = $name;
        $role->email = $request->email;
        $role->description = $request->description;
        $role->save();

        if (isset($request->permissions)) {
            $permissions = $request->permissions;
            //Looping thru selected permissions
            foreach ($permissions as $permission) {
                $p = Permission::where('id', '=', $permission)->firstOrFail();
                //Fetch the newly created role and assign permission
                $role = Role::where('name', '=', $name)->first();
                $role->givePermissionTo($p);
            }
        }

        return redirect()->route('roles.index')->with('status', 'Role ' . $role->name . ' added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {

        $permissions = Permission::all();

        $grouped_permissions = $this->groupPermission($permissions);

        return view('roles.edit', [
            'role' => $role->load(['permissions']),
            'permissions' => $grouped_permissions
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {

        $this->validate($request, [
            'name' => 'required|unique:roles,name,' . $role->id,
        ]);

        $input = $request->except(['permissions']);
        $role->fill($input)->save();

        $p_all = Permission::all();

        foreach ($p_all as $p) {
            $role->revokePermissionTo($p);
        }

        if (isset($request->permissions)) {
            $permissions = $request->permissions;
            foreach ($permissions as $permission) {
                $p = Permission::where('id', '=', $permission)->firstOrFail(); //Get corresponding form //permission in db
                $role->givePermissionTo($p);  //Assign permission to role
            }
        }

        return redirect()->route('roles.index')
            ->with('status', 'Role ' . $role->name . ' updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();

        return redirect()->route('roles.index')
            ->with('status', 'Role ' . $role->name . ' deleted!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \Spatie\Permission\Models\Permission $permissions
     * @return \Illuminate\Http\Response
     */
    public function groupPermission($permissions)
    {
        foreach ($permissions as $permission) {
            $p = explode('_', $permission->name, 2);
            $group = $p[0];
            $action = $p[1];
            $values = [
                'id' => $permission->id,
                'name' => $action,
                'value' => $permission->name
            ];
            $grouped_permissions[$group][] = $values;
        }

        return $grouped_permissions;
    }
}

resources/views/roles/edit.blade.php
@extends('layouts.app', ['title' => 'Edit Role'])

@section('content')

@include('layouts.partials.header', ['title' => 'Edit '.$role->name])
<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-body">
                    <form method="POST" action="{{route('roles.update',$role)}}">
                        @method('PUT')
                        @csrf
                        <!-- Role Name -->
                        <div class="form-row mb-2">
                            <label class="col-md-2 col-form-label">Role Name</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" name="name" value='{{ $role->name }}'>
                            </div>
                        </div>
                        <!-- Role Email -->
                        <div class="form-row mb-2">
                            <label class="col-md-2 col-form-label">Role Email (For notification)</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" name="email" value='{{ $role->email }}'>
                            </div>
                        </div>
                        <!-- Role Description -->
                        <div class="form-group row">
                            <label class="col-md-2 col-form-label">Description</label>
                            <div class="col-md-10">
                                <textarea id="create-role-description" type="text" class="form-control" name="description">{{ $role->description }}</textarea>
                            </div>
                        </div>
                        <div class="form-row">
                            <label class="col-md-2 col-form-label">Permissions</label>
                            <div class="col-md-10">
                                @if(!empty($permissions))
                                @foreach($permissions as $key => $permission)
                                <div class="form-group">
                                    <label class="form-label">{{ ucfirst($key) }}</label>
                                    <div class="selectgroup selectgroup-pills">
                                        @foreach($permission as $action)
                                        <label class="selectgroup-item">
                                            <input type="checkbox" name="permissions[]" class="selectgroup-input" value="{{ $action['id'] }}" {{ in_array($action['id'],$role->permissions->pluck('id')->toArray())?'checked':'' }}>
                                            <span class="selectgroup-button">{{ ucfirst($action['name']) }}</span>
                                        </label>
                                        @endforeach
                                    </div>
                                </div>
                                @endforeach
                                @else
                                <p class="mb-0">No Permission created.</p>
                                @endif
                            </div>
                        </div>
                        <div class="d-flex justify-content-end">
                            <div>
                                <button type="button" class="btn btn-danger" onclick="event.preventDefault();
                                    document.getElementById('delete-role-form').submit();">
                                    Delete
                                </button>
                                <button type="submit" class="btn btn-success">Update</button>
                            </div>
                        </div>
                    </form>
                    <form id="delete-role-form" action="{{ route('roles.destroy',$role) }}" method="POST" style="display: none;">
                        @method('DELETE')
                        @csrf
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app', ['title' => 'Roles'])

@section('content')

@include('layouts.partials.header', ['title' => 'Manage Roles'])   
<div class="container-fluid mt--7">
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <h3 class="mb-0">Roles</h3>
                        </div>
                        <div class="col-4 text-right">
                            <button class="btn btn-sm btn-primary" data-toggle="modal" data-target="#modal-create-role">Add role</button>
                        </div>
                    </div>
                </div>

                <div class="col-12">
                    @if (session('status'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('status') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif
                </div>

                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        @if($roles->count() > 0)
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Description</th>
                                <th scope="col">Email</th>
                                <th scope="col">Permissions</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($roles as $role)
                            <tr>
                                <td>
                                    {{ $role->name }}
                                </td>
                                <td>
                                    {{ $role->description }}
                                </td>
                                <td>
                                    {{ $role->email }}
                                </td>
                                <td>
                                    {{ $role->permissions->count() }}
                                </td>
                                <!-- Revoke Button -->
                                <td>
                                    <a href="{{ route('roles.edit', $role) }}" class="btn btn-primary btn-sm"><i class="far fa-edit"></i> Edit</a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                        @else
                        <tr>
                            <td colspan="5">No role created.</td>
                        </tr>
                        @endif
                    </table>
                </div>
            </div>
        </div>
    </div>
    @include('layouts.footers.auth')
</div>

<!-- Create Role Modal -->
<div class="modal fade" id="modal-create-role" tabindex="-1" role="dialog" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">
                    Create Role
                </h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>

            <div class="modal-body">
                <!-- Create Role Form -->
                <form id="add-role-form" role="form" method="POST" action="{{ route('roles.store') }}">
                    @csrf
                    <!-- Name -->
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Role Name</label>
                        <div class="col-md-10">
                            <input id="create-role-name" type="text" class="form-control" name="name">
                        </div>
                    </div>
                    <!-- Email -->
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Email</label>
                        <div class="col-md-10">
                            <input id="create-role-description" type="text" class="form-control" name="email">
                        </div>
                    </div>
                    <!-- Description -->
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Description</label>
                        <div class="col-md-10">
                            <textarea id="create-role-description" type="text" class="form-control" name="description"></textarea>
                        </div>
                    </div>
                    <!-- Permission-->
                    <div class="form-row">
                        <label class="col-md-2 col-form-label">Permissions</label>
                        <div class="col-md-10">
                            @if(!empty($permissions))
                            @foreach($permissions as $key => $permission)
                            <div class="form-group">
                                <label class="form-label">{{ ucfirst($key) }}</label>
                                <div class="selectgroup selectgroup-pills">
                                    @foreach($permission as $action)
                                    <label class="selectgroup-item">
                                        <input type="checkbox" name="permissions[]" class="selectgroup-input" value="{{ $action['id'] }}">
                                        <span class="selectgroup-button">{{ ucfirst($action['name']) }}</span>
                                    </label>
                                    @endforeach
                                </div>
                            </div>
                            @endforeach
                            @else
                            <p class="mb-0">No Permission created.</p>
                            @endif
                        </div>
                    </div>
                </form>
            </div>

            <!-- Modal Actions -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="add-role-form-submit" type="button" class="btn btn-primary">
                    Create
                </button>
            </div>
        </div>
    </div>
</div>
<!-- End Create Role Modal -->

@endsection

@push('js')
<script type="text/javascript">
    $('#add-role-form-submit').on('click', function(event) {
        $('#add-role-form').submit();
    });
</script>
@endpush